# Standard BLS report format  	  	  
#  	  	  
# DO NOT EDIT THIS FILE!!!  	  	  


def print_report(dat):  	  	  
    print(f"""\
[==========================================================]
[ US BLS Quarterly Census of Employment and Wages for {dat['year']} ]
[==========================================================]

Statistics over all industries
-----------------------------------------------------------
Number of FIPS areas in report       {dat['all']['num_areas']:,}

Total annual wages                   ${dat['all']['total_annual_wages']:,}
Area with maximum annual wages       {dat['all']['max_annual_wage'][0]}
Maximum reported wage                ${dat['all']['max_annual_wage'][1]:,}

Total number of establishments       {dat['all']['total_estab']:,}
Area with most establishments        {dat['all']['max_estab'][0]}
Maximum # of establishments          {dat['all']['max_estab'][1]:,}

Total annual employment level        {dat['all']['total_empl']:,}
Area with maximum employment         {dat['all']['max_empl'][0]}
Maximum reported employment level    {dat['all']['max_empl'][1]:,}


Statistics in the software publishing industry
-----------------------------------------------------------
Number of FIPS areas in report       {dat['soft']['num_areas']:,}

Total annual wages                   ${dat['soft']['total_annual_wages']:,}
Area with maximum annual wages       {dat['soft']['max_annual_wage'][0]}
Maximum reported wage                ${dat['soft']['max_annual_wage'][1]:,}

Total number of establishments       {dat['soft']['total_estab']:,}
Area with most establishments        {dat['soft']['max_estab'][0]}
Maximum # of establishments          {dat['soft']['max_estab'][1]:,}

Total annual employment level        {dat['soft']['total_empl']:,}
Area with maximum employment         {dat['soft']['max_empl'][0]}
Maximum reported employment level    {dat['soft']['max_empl'][1]:,}""")  	  	  
